//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestORM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bibliographieEntities : DbContext
    {
        public bibliographieEntities()
            : base("name=bibliographieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auteur> Auteurs { get; set; }
        public virtual DbSet<Editeur> Editeurs { get; set; }
        public virtual DbSet<Livre> Livres { get; set; }
        public virtual DbSet<VueLivre> VueLivres { get; set; }
    }
}
