//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class VueLivre
    {
        public int Id_Livre { get; set; }
        public string Titre_Livre { get; set; }
        public int Annee_sortie { get; set; }
        public string Editeur { get; set; }
    }
}
